[workspace]
members = [
    "engine",
    "players",
    "local",
    "deck_builder",
    "proto",
    "server",
    "clients",
]

default-members = ["local"]

[profile.release]
debug = 1

[profile.dev]
opt-level = 3
